version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester-uv
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            uv venv --python 3.9 /usr/local/share/virtualenvs/tap-intacct
            source /usr/local/share/virtualenvs/tap-intacct/bin/activate
            uv pip install -U 'pip<19.2' 'setuptools<51.0.0'
            uv pip install .[dev]
      - add_ssh_keys
      - run:
          name: 'Pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-intacct/bin/activate
            uv pip install pylint
            pylint tap_intacct
workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
  build_daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: circleci-user
